"""Shared broker topic and queue names for Helix."""

from __future__ import annotations

TRADE_CREATED_TOPIC = "trade.created"
TRADE_AMENDED_TOPIC = "trade.amended"
TRADE_CANCELLED_TOPIC = "trade.cancelled"
MARKETDATA_UPDATED_TOPIC = "marketdata.updated"
PORTFOLIO_UPDATED_TOPIC = "portfolio.updated"
PNL_UPDATED_TOPIC = "pnl.updated"
RISK_UPDATED_TOPIC = "risk.updated"
ALERT_CREATED_TOPIC = "alert.created"

KAFKA_TOPICS = (
    TRADE_CREATED_TOPIC,
    TRADE_AMENDED_TOPIC,
    TRADE_CANCELLED_TOPIC,
    MARKETDATA_UPDATED_TOPIC,
    PORTFOLIO_UPDATED_TOPIC,
    PNL_UPDATED_TOPIC,
    RISK_UPDATED_TOPIC,
    ALERT_CREATED_TOPIC,
)

PORTFOLIO_FULL_REVALUE_QUEUE = "portfolio.full_revalue"
REBUILD_POSITIONS_QUEUE = "rebuild.positions"
RECOMPUTE_RISK_FULL_QUEUE = "recompute.risk.full"
REPORT_GENERATE_QUEUE = "report.generate"

RABBITMQ_QUEUES = (
    PORTFOLIO_FULL_REVALUE_QUEUE,
    REBUILD_POSITIONS_QUEUE,
    RECOMPUTE_RISK_FULL_QUEUE,
    REPORT_GENERATE_QUEUE,
)
